name: Release

on:
  push:
    tags:
      - "v*"

env:
  COMPONENT_NAME: solis_cloud_control

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set version number
        run: |
          version=${GITHUB_REF_NAME#v}
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/manifest.json"

      - name: Zip ${{ env.COMPONENT_NAME }} directory
        run: |
          cd "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}"
          zip ${{ env.COMPONENT_NAME }}.zip -r ./

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/${{ env.COMPONENT_NAME }}.zip
